### ISSUE TITLE
spurious disconnect

### ISSUE THREAD

**Issue by umlaeute** [RITlug/teleirc#67]
this morning my teleirc bridge suddenly disconnected from the IRC.

the relevant logs from my docker-container running teleirc are:
~~~
Sep 06 07:33:20 docker1 env[9707]: teleirc_1  | Unhandled rejection TimeoutError: operation timed out
Sep 06 07:33:20 docker1 env[9707]: teleirc_1  |     at afterTimeout (/opt/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/timers.js:16:15)
Sep 06 07:33:20 docker1 env[9707]: teleirc_1  |     at Timeout.timeoutTimeout [as _onTimeout] (/opt/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/tim
Sep 06 07:33:20 docker1 env[9707]: teleirc_1  |     at ontimeout (timers.js:498:11)
Sep 06 07:33:20 docker1 env[9707]: teleirc_1  |     at tryOnTimeout (timers.js:323:5)
Sep 06 07:33:20 docker1 env[9707]: teleirc_1  |     at Timer.listOnTimeout (timers.js:290:5)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  | Unhandled rejection RequestError: Error: connect EADDRNOTAVAIL 2001:67c:4e8:f004::9:443 - Local (:::0)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at new RequestError (/opt/teleirc/node_modules/request-promise/lib/errors.js:11:15)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at Request.RP$callback [as _callback] (/opt/teleirc/node_modules/request-promise/lib/rp.js:60:32)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at self.callback (/opt/teleirc/node_modules/request/request.js:186:22)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at emitOne (events.js:116:13)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at Request.emit (events.js:211:7)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at Request.onRequestError (/opt/teleirc/node_modules/request/request.js:845:8)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at emitOne (events.js:116:13)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at ClientRequest.emit (events.js:211:7)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at TLSSocket.socketErrorListener (_http_client.js:387:9)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at emitOne (events.js:116:13)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at TLSSocket.emit (events.js:211:7)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Sep 06 07:33:25 docker1 env[9707]: teleirc_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)
~~~

the container is configured to restart on exit. however it seems that these "unhandled errors" are not fatal, but the bridge never attempts to recover from them, thus keeping the bridge in disconnected state.

(sidenote: i have no clue what happened on the telegram side, as i'm not subscribed there)

**Comment by umlaeute** [comment]
also, the `Unhandled rejection TimeoutError: operation timed out` is happening regularily (about 23 times in the last 36 hours), and usually nothing happens (at least on the IRC side). therefore i don't know how alarming this error should be.

also: the telegram group is not exactly very busy, so i don't know whether messages were lost.

**Comment by jwflory** [comment]
@umlaeute Thanks for reporting this and thank you for being patient for a reply. @thenaterhood submitted PR #74 which should fix this (since the bot now triggers a hard crash on failure). I'm going to close this as resolved. :clapper: 

Please try testing the bot with the `master` branch and let us know if you are still experiencing this issue. We'll work on cutting a new release in the next month.

**Comment by umlaeute** [comment]
a hard crash sounds great (as it is something, the caller can react on).
i'll try to test in the next few days and report back.

**Comment by jwflory** [comment]
@umlaeute Thanks! Feel free to reopen this issue if you still notice the issue.
